apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: oficina-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: oficina-api-deployment
  minReplicas: 1
  maxReplicas: 3 # Limite seguro para o orçamento do laboratório
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # Se a média de CPU dos pods passar de 70%, cria um novo clone