apiVersion: v1
kind: Secret
metadata:
  name: oficina-api-secret
  labels:
    app: oficina-api
type: Opaque
data:
  # No Kubernetes, os Secrets precisam estar em formato Base64.
  # ZGJhZG1pbg== é a palavra "dbadmin" em Base64
  SPRING_DATASOURCE_USERNAME: "ZGJhZG1pbg=="

  # YWRtaW5wYXNzd29yZA== é a palavra "adminpassword" em Base64
  SPRING_DATASOURCE_PASSWORD: "YWRtaW5wYXNzd29yZA=="