name: CI/CD Pipeline - Oficina API

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: oficina-api-dev-repo
  EKS_CLUSTER_NAME: oficina-api-dev-cluster
  RDS_INSTANCE_IDENTIFIER: oficina-api-dev-postgres

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ============================================================
      # CI
      # ============================================================

      - name: 1. Checkout do código
        uses: actions/checkout@v5

      - name: 2. Configurar Java 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: 3. Compilar e executar testes
        run: mvn clean package

      # ============================================================
      # CD - somente main
      # ============================================================

      - name: 4. Autenticar na AWS
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 5. Login no Amazon ECR
        if: github.event_name == 'push'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: 6. Build e Push da imagem Docker
        if: github.event_name == 'push'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          DOCKER_IMAGE="$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

          echo "Gerando imagem: $DOCKER_IMAGE"

          docker build -t "$DOCKER_IMAGE" .
          docker push "$DOCKER_IMAGE"

      - name: 7. Configurar acesso ao cluster EKS
        if: github.event_name == 'push'
        run: |
          aws eks update-kubeconfig \
            --region "$AWS_REGION" \
            --name "$EKS_CLUSTER_NAME"

          kubectl get nodes

      - name: 8. Buscar configurações do RDS
        if: github.event_name == 'push'
        run: |
          DB_ENDPOINT=$(aws rds describe-db-instances \
            --db-instance-identifier "$RDS_INSTANCE_IDENTIFIER" \
            --query 'DBInstances[0].Endpoint.Address' \
            --output text)

          SECRET_ARN=$(aws rds describe-db-instances \
            --db-instance-identifier "$RDS_INSTANCE_IDENTIFIER" \
            --query 'DBInstances[0].MasterUserSecret.SecretArn' \
            --output text)

          echo "DB_ENDPOINT=$DB_ENDPOINT" >> "$GITHUB_ENV"
          echo "DB_SECRET_ARN=$SECRET_ARN" >> "$GITHUB_ENV"

      - name: 9. Criar/atualizar Secret do Kubernetes
        if: github.event_name == 'push'
        run: |
          # Credenciais do PostgreSQL
          DB_SECRET_VALUE=$(aws secretsmanager get-secret-value \
            --secret-id "$DB_SECRET_ARN" \
            --query SecretString \
            --output text)

          DB_USERNAME=$(echo "$DB_SECRET_VALUE" | jq -r '.username')
          DB_PASSWORD=$(echo "$DB_SECRET_VALUE" | jq -r '.password')

          # Chave utilizada para assinatura/validação dos JWTs
          JWT_SECRET=$(aws secretsmanager get-secret-value \
          --secret-id oficina-auth-jwt-secret \
          --query SecretString \
          --output text)

          # Evita que as credenciais apareçam nos logs
          echo "::add-mask::$DB_USERNAME"
          echo "::add-mask::$DB_PASSWORD"
          echo "::add-mask::$JWT_SECRET"

          kubectl create secret generic oficina-api-secret \
            --from-literal=SPRING_DATASOURCE_USERNAME="$DB_USERNAME" \
            --from-literal=SPRING_DATASOURCE_PASSWORD="$DB_PASSWORD" \
            --from-literal=JWT_SECRET="$JWT_SECRET" \
            --from-literal=NEW_RELIC_LICENSE_KEY="${{ secrets.NEW_RELIC_LICENSE_KEY }}"
            --dry-run=client \
            -o yaml | kubectl apply -f -

      - name: 10. Preparar manifests Kubernetes
        if: github.event_name == 'push'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          mkdir -p /tmp/oficina-k8s

          DOCKER_IMAGE="$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

          sed "s|\${DB_ENDPOINT}|$DB_ENDPOINT|g" \
            k8s/configmap.yaml \
            > /tmp/oficina-k8s/configmap.yaml

          sed "s|\${DOCKER_IMAGE}|$DOCKER_IMAGE|g" \
            k8s/deployment.yaml \
            > /tmp/oficina-k8s/deployment.yaml

          cp k8s/service.yaml /tmp/oficina-k8s/service.yaml
          cp k8s/hpa.yaml /tmp/oficina-k8s/hpa.yaml

      - name: 11. Deploy no Kubernetes
        if: github.event_name == 'push'
        run: |
          kubectl apply -f /tmp/oficina-k8s/configmap.yaml
          kubectl apply -f /tmp/oficina-k8s/deployment.yaml
          kubectl apply -f /tmp/oficina-k8s/service.yaml
          kubectl apply -f /tmp/oficina-k8s/hpa.yaml

      - name: 12. Aguardar rollout da aplicação
        if: github.event_name == 'push'
        run: |
          kubectl rollout status \
            deployment/oficina-api-deployment \
            --timeout=180s

      - name: 13. Exibir recursos implantados
        if: github.event_name == 'push'
        run: |
          kubectl get pods
          kubectl get service oficina-api-service
          kubectl get hpa oficina-api-hpa